### ISSUE TITLE
select 2 version update

### ISSUE THREAD

**Issue by akankov** [pinano/select2-bundle#4]
Hey, man. select 2 version 4.0.0 available. Do you want to update your bandle?

**Comment by pinano** [comment]
Now that v4.0.0 final is out I will try to do my best to update the bundle this week. Apologies for the delay, I have just been busy with work and family :)

**Comment by RichardFrontwise** [comment]
Thanks for the update!
However, the select2.min.js file is not included, which breaks backwards compatibility.
Is it possible to add this file, or to update the documentation to reflect this change?

**Comment by pinano** [comment]
I generally don't like to include minified files, I find it redundant since you can just apply an assetic filter (such as uglify-js or yui-compressor) to minify the file. However, if you would like to have the min.js version I can include it for you, no problem.

**Comment by pinano** [comment]
Minified js and css files have been included in the 4.0.0 release
